In [1]:
import pandas as pd

In [2]:
population2009 = pd.read_excel('Iris - Population/BTX_IC_POP_2009.xls')
population2010 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2010.xls')
population2011 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2011.xls')
population2012 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2012.xls')
population2013 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2013.xls')
population2014 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2014.xls')
population2015 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2015.xls')
population2016 = pd.read_excel('Iris - Population/base-ic-evol-struct-pop-2016.xls')
population2017 = pd.read_csv('Iris - Population/base-ic-evol-struct-pop-2017.CSV', sep=";", low_memory=False)
population2018 = pd.read_csv('Iris - Population/base-ic-evol-struct-pop-2018.CSV', sep=";",low_memory=False)

In [3]:
population2009 = population2009[population2009.COM=='69081']
population2010 = population2010[population2010.COM=='69081']
population2011 = population2011[population2011.COM=='69081']
population2012 = population2012[population2012.COM=='69081']
population2013 = population2013[population2013.COM=='69081']
population2014 = population2014[population2014.COM=='69081']
population2015 = population2015[population2015.COM=='69081']
population2016 = population2016[population2016.COM=='69081']
population2017 = population2017[population2017.COM=='69081']
population2018 = population2018[population2018.COM=='69081']

In [4]:
population2009['ANNEE'] = 2009
population2010['ANNEE'] = 2010
population2011['ANNEE'] = 2011
population2012['ANNEE'] = 2012
population2013['ANNEE'] = 2013
population2014['ANNEE'] = 2014
population2015['ANNEE'] = 2015
population2016['ANNEE'] = 2016
population2017['ANNEE'] = 2017
population2018['ANNEE'] = 2018

In [5]:
df_population2009 = population2009[['IRIS', 'COM','ANNEE','P09_POP','P09_POP0002', 'P09_POP0305', 'P09_POP0610', 'P09_POP1117', 'P09_POP1824',
                                    'P09_POP2539','P09_POP4054','P09_POP5564','P09_POP6579', 'P09_POP80P']]

df_population2009 = (df_population2009
                            .rename(columns={'P09_POP':'P_POP', 'P09_POP0002':'P_POP0002', 'P09_POP0305':'P_POP0305', 'P09_POP0610':'P_POP0610',
                                             'P09_POP1117':'P_POP1117', 'P09_POP1824':'P_POP1824', 'P09_POP2539':'P_POP2539', 'P09_POP4054':'P_POP4054',
                                             'P09_POP5564':'P_POP5564', 'P09_POP6579':'P_POP6579', 'P09_POP80P':'P_POP80P'}))

In [6]:
df_population2010 = population2010[['IRIS', 'COM','ANNEE','P10_POP','P10_POP0002', 'P10_POP0305', 'P10_POP0610', 'P10_POP1117', 'P10_POP1824',
                                    'P10_POP2539','P10_POP4054','P10_POP5564','P10_POP6579', 'P10_POP80P']]

df_population2010 = (df_population2010
                            .rename(columns={'P10_POP':'P_POP', 'P10_POP0002':'P_POP0002', 'P10_POP0305':'P_POP0305', 'P10_POP0610':'P_POP0610',
                                             'P10_POP1117':'P_POP1117', 'P10_POP1824':'P_POP1824', 'P10_POP2539':'P_POP2539', 'P10_POP4054':'P_POP4054',
                                             'P10_POP5564':'P_POP5564', 'P10_POP6579':'P_POP6579', 'P10_POP80P':'P_POP80P'}))

In [7]:
df_population2011 = population2011[['IRIS', 'COM','ANNEE','P11_POP','P11_POP0002', 'P11_POP0305', 'P11_POP0610', 'P11_POP1117', 'P11_POP1824',
                                    'P11_POP2539','P11_POP4054','P11_POP5564','P11_POP6579', 'P11_POP80P']]

df_population2011 = (df_population2011
                            .rename(columns={'P11_POP':'P_POP', 'P11_POP0002':'P_POP0002', 'P11_POP0305':'P_POP0305', 'P11_POP0610':'P_POP0610',
                                             'P11_POP1117':'P_POP1117', 'P11_POP1824':'P_POP1824', 'P11_POP2539':'P_POP2539', 'P11_POP4054':'P_POP4054',
                                             'P11_POP5564':'P_POP5564', 'P11_POP6579':'P_POP6579', 'P11_POP80P':'P_POP80P'}))

In [8]:
df_population2012 = population2012[['IRIS', 'COM','ANNEE','P12_POP','P12_POP0002', 'P12_POP0305', 'P12_POP0610', 'P12_POP1117', 'P12_POP1824',
                                    'P12_POP2539','P12_POP4054','P12_POP5564','P12_POP6579', 'P12_POP80P']]

df_population2012 = (df_population2012
                            .rename(columns={'P12_POP':'P_POP', 'P12_POP0002':'P_POP0002', 'P12_POP0305':'P_POP0305', 'P12_POP0610':'P_POP0610',
                                             'P12_POP1117':'P_POP1117', 'P12_POP1824':'P_POP1824', 'P12_POP2539':'P_POP2539', 'P12_POP4054':'P_POP4054',
                                             'P12_POP5564':'P_POP5564', 'P12_POP6579':'P_POP6579', 'P12_POP80P':'P_POP80P'}))

In [9]:
df_population2013 = population2013[['IRIS', 'COM','ANNEE','P13_POP','P13_POP0002', 'P13_POP0305', 'P13_POP0610', 'P13_POP1117', 'P13_POP1824',
                                    'P13_POP2539','P13_POP4054','P13_POP5564','P13_POP6579', 'P13_POP80P']]

df_population2013 = (df_population2013
                            .rename(columns={'P13_POP':'P_POP', 'P13_POP0002':'P_POP0002', 'P13_POP0305':'P_POP0305', 'P13_POP0610':'P_POP0610',
                                             'P13_POP1117':'P_POP1117', 'P13_POP1824':'P_POP1824', 'P13_POP2539':'P_POP2539', 'P13_POP4054':'P_POP4054',
                                             'P13_POP5564':'P_POP5564', 'P13_POP6579':'P_POP6579', 'P13_POP80P':'P_POP80P'}))

In [10]:
df_population2014 = population2014[['IRIS', 'COM','ANNEE','P14_POP','P14_POP0002', 'P14_POP0305', 'P14_POP0610', 'P14_POP1117', 'P14_POP1824',
                                    'P14_POP2539','P14_POP4054','P14_POP5564','P14_POP6579', 'P14_POP80P']]

df_population2014 = (df_population2014
                            .rename(columns={'P14_POP':'P_POP', 'P14_POP0002':'P_POP0002', 'P14_POP0305':'P_POP0305', 'P14_POP0610':'P_POP0610',
                                             'P14_POP1117':'P_POP1117', 'P14_POP1824':'P_POP1824', 'P14_POP2539':'P_POP2539', 'P14_POP4054':'P_POP4054',
                                             'P14_POP5564':'P_POP5564', 'P14_POP6579':'P_POP6579', 'P14_POP80P':'P_POP80P'}))

In [11]:
df_population2015 = population2015[['IRIS', 'COM','ANNEE','P15_POP','P15_POP0002', 'P15_POP0305', 'P15_POP0610', 'P15_POP1117', 'P15_POP1824',
                                    'P15_POP2539','P15_POP4054','P15_POP5564','P15_POP6579', 'P15_POP80P']]

df_population2015 = (df_population2015
                            .rename(columns={'P15_POP':'P_POP', 'P15_POP0002':'P_POP0002', 'P15_POP0305':'P_POP0305', 'P15_POP0610':'P_POP0610',
                                             'P15_POP1117':'P_POP1117', 'P15_POP1824':'P_POP1824', 'P15_POP2539':'P_POP2539', 'P15_POP4054':'P_POP4054',
                                             'P15_POP5564':'P_POP5564', 'P15_POP6579':'P_POP6579', 'P15_POP80P':'P_POP80P'}))

In [12]:
df_population2016 = population2016[['IRIS', 'COM','ANNEE','P16_POP','P16_POP0002', 'P16_POP0305', 'P16_POP0610', 'P16_POP1117', 'P16_POP1824',
                                    'P16_POP2539','P16_POP4054','P16_POP5564','P16_POP6579', 'P16_POP80P']]

df_population2016 = (df_population2016
                            .rename(columns={'P16_POP':'P_POP', 'P16_POP0002':'P_POP0002', 'P16_POP0305':'P_POP0305', 'P16_POP0610':'P_POP0610',
                                             'P16_POP1117':'P_POP1117', 'P16_POP1824':'P_POP1824', 'P16_POP2539':'P_POP2539', 'P16_POP4054':'P_POP4054',
                                             'P16_POP5564':'P_POP5564', 'P16_POP6579':'P_POP6579', 'P16_POP80P':'P_POP80P'}))

In [13]:
df_population2017 = population2017[['IRIS', 'COM','ANNEE','P17_POP','P17_POP0002', 'P17_POP0305', 'P17_POP0610', 'P17_POP1117', 'P17_POP1824',
                                    'P17_POP2539','P17_POP4054','P17_POP5564','P17_POP6579', 'P17_POP80P']]

df_population2017 = (df_population2017
                            .rename(columns={'P17_POP':'P_POP', 'P17_POP0002':'P_POP0002', 'P17_POP0305':'P_POP0305', 'P17_POP0610':'P_POP0610',
                                             'P17_POP1117':'P_POP1117', 'P17_POP1824':'P_POP1824', 'P17_POP2539':'P_POP2539', 'P17_POP4054':'P_POP4054',
                                             'P17_POP5564':'P_POP5564', 'P17_POP6579':'P_POP6579', 'P17_POP80P':'P_POP80P'}))

In [14]:
df_population2018 = population2018[['IRIS', 'COM','ANNEE','P18_POP','P18_POP0002', 'P18_POP0305', 'P18_POP0610', 'P18_POP1117', 'P18_POP1824',
                                    'P18_POP2539','P18_POP4054','P18_POP5564','P18_POP6579', 'P18_POP80P']]

df_population2018 = (df_population2018
                            .rename(columns={'P18_POP':'P_POP', 'P18_POP0002':'P_POP0002', 'P18_POP0305':'P_POP0305', 'P18_POP0610':'P_POP0610',
                                             'P18_POP1117':'P_POP1117', 'P18_POP1824':'P_POP1824', 'P18_POP2539':'P_POP2539', 'P18_POP4054':'P_POP4054',
                                             'P18_POP5564':'P_POP5564', 'P18_POP6579':'P_POP6579', 'P18_POP80P':'P_POP80P'}))

In [15]:
df_population = pd.concat([df_population2009,
                         df_population2010,
                         df_population2011,
                         df_population2012,
                         df_population2013,
                         df_population2014,
                         df_population2015,
                         df_population2016,
                         df_population2017,
                         df_population2018], axis=0).sort_values('ANNEE').reset_index(drop=True)

In [16]:
pd.set_option('display.max_columns', None)
df_population

,IRIS,COM,ANNEE,P_POP,P_POP0002,P_POP0305,P_POP0610,P_POP1117,P_POP1824,P_POP2539,P_POP4054,P_POP5564,P_POP6579,P_POP80P
0,690810101,69081,2009,1803.691771,106.057485,84.072027,164.142864,146.651460,172.398278,322.632992,340.590665,199.944630,219.284484,47.916886
1,690810102,69081,2009,1869.662835,71.525414,89.403236,132.318560,196.411558,147.652208,368.248638,376.127399,161.687115,248.098823,78.189885
2,690810103,69081,2009,103.329184,0.000000,0.000000,6.351120,24.952228,9.338789,11.555600,28.016367,2.987669,13.249654,6.877758
3,690810104,69081,2009,1732.375375,40.769495,60.781735,103.768402,235.025409,162.259629,191.977348,402.149916,269.337129,217.281893,49.024419
4,690810105,69081,2009,2079.352127,46.131555,45.847234,214.310085,208.989408,206.565688,312.720721,466.195249,231.864804,273.510074,73.217308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,690810104,69081,2018,2060.227971,53.581142,91.580660,171.464046,244.973228,188.761727,224.813432,444.440282,273.970704,261.156687,105.486061
86,690810105,69081,2018,2022.784953,47.161055,47.374789,153.491108,186.202200,217.997812,178.526751,431.359092,369.592423,268.585551,122.494174
87,690810201,69081,2018,2430.780534,46.332041,48.500391,124.297726,174.986810,940.394628,351.816652,308.156613,147.170851,227.686961,61.437861
88,690810202,69081,2018,2416.444115,68.747225,72.347372,208.160415,259.345553,246.909187,341.012745,394.975348,198.209460,333.151459,293.585352
89,690810302,69081,2018,2744.340057,91.865427,53.239992,107.659796,211.685311,241.662770,339.305922,456.065649,302.675198,586.904267,353.275725

In [17]:
df_population.to_csv('Data/Iris - population.csv')

In [ ]:
print("Base Population chargée !")